services:

  web:
    volumes:
      - static_data:/vol/web
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol
    ports:
      - "80:80"

volumes:
  static_data:
