# Generated by Django 4.1.7 on 2023-02-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('tables', models.PositiveSmallIntegerField()),
                ('big_blind', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_per_table', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rebuys', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hands', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-end'],
            },
        ),
    ]
